version: "3.8"
services:
  web:
    depends_on:
      - db
    image: "jrodrigv/compose-net-web:latest"
    ports:
      - target: 80
        published: 8080
        mode: ingress
    networks:
      - frontend   
      - backend
    deploy:
      replicas: 2

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y" 
    networks:
      - backend
  
networks:
  frontend:
  backend: